### ISSUE TITLE
offset_index_store: Could not truncate

### ISSUE THREAD

**Issue by mattievk** [brentp/python-giggle#3]
When trying to create an index using one of the test files (`python-giggle\lib\giggle\test\data\1k.sort.bed.gz`) using the following code:
```
from giggle import Giggle 
index = Giggle.create("index", "1k.sort.bed.gz")
```
I get the following error:
`python: offset_index_store: Could not truncate.: Invalid argument`

It looks like the error is occurring from `offset_index.c` line 170:
```
if ( ret != 0 )
        err(1, "offset_index_store: Could not truncate.");
```
I have no clue as to why this is happening even with the test data (tried others as well). I am using python 3.6 but got the same error on python 2.7.

**Comment by brentp** [comment]
this is not happening for me on the same test file on python 2.7 or python 3.6.4.

```ipython
(py364) brentp@lorax:~/src/giggle/test/data$ ipython
Python 3.6.4 |Anaconda custom (64-bit)| (default, Jan 16 2018, 18:10:19) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from giggle import Giggle

In [2]: index = Giggle.create("index2", "1k.sort.bed.gz")

In [3]: index = Giggle.create("index3", "*1k.sort.bed.gz")
```

any idea why I can't reproduce the issue?

**Comment by mattievk** [comment]
I think the problem was underlying the linux subsystem for windows. I decides to switch to a complete installation of Ubuntu and try it on there and now it works fine. Finally... Thanks very much!

**Comment by brentp** [comment]
glad to hear it. thanks for following up.
